language: c++

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - CXX_COMPILER=g++-4.9
        - C_COMPILER=gcc-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - CXX_COMPILER=g++-5
        - C_COMPILER=gcc-5

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libopencv-dev

script:
  - cmake -E make_directory build && cmake -E chdir build cmake -DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_C_COMPILER=$C_COMPILER  ..
  - cmake --build build -- all test
